set nocompatible

filetype plugin indent on

syntax on

if has("termguicolors")
    set termguicolors
endif

" Color scheme
if !has("gui") && $TERM ==# "linux"
    colors pablo
else
    set background=dark
    colors one
endif

if has("gui")
    if has("win32")
        set guifont=Consolas:h12:cANSI
    else
        set guifont=JetBrains\ Mono\ Regular\ 12
    endif
    set guioptions-=T
    set guioptions-=t
endif

if has("gui") || has("win32")
    behave mswin
endif

" Use ~/.vim on Windows too, instead of ~/vimfiles
if has("win32")
    set runtimepath^=~/.vim
    set runtimepath+=~/.vim/after
    set packpath^=~/.vim
endif

" Disable Generation of Backup Files
set nobackup
set noswapfile

" Completion options
set completeopt=menu,longest
set wildmode=longest,list
set wildignore+=*.pyc

" character encoding
set enc=utf-8

" Do not wrap lines automatically
set nowrap

" Highlight current line in insert mode. Disabled for performance.
" autocmd InsertLeave * se nocul
" autocmd InsertEnter * se cul

set tabstop=4
set shiftwidth=4

" Do smart case matching
set smarttab

" no tabs! spaces only..
set expandtab

" if it looks like a tab, we can delete it like a tab
set softtabstop=4

" new line has indentation equal to previous line
set autoindent

" backspace over autoindent, end of line (to join lines), and preexisting test
set backspace=indent,eol,start

" toggle paste
set pastetoggle=<F2>

" Show line numbers by default
set number

" Use incremental searching
set incsearch

" Case insensitive search
set ignorecase

" Do not highlight search results
set nohlsearch

" Scroll when cursor gets within 3 characters of top/bottom edge
set scrolloff=3

" Remember things between sessions
"
" '20  - remember marks for 20 previous files
" \"50 - save 50 lines for each register
" :50  - remember 50 items in command-line history
set viminfo='20,\"50,:50

" Remember up to 100 'colon' commmands and search patterns
" set history=100

" {{{ Command mappings

" backspace in Visual mode deletes selection
vnoremap <BS> d

" CTRL-C is Copy
vnoremap <C-C> "+y

" CTRL-V is Paste
noremap <C-V>		"+gP
cnoremap <C-V>		<C-R>+

exe 'inoremap <script> <C-V>' paste#paste_cmd['i']
exe 'vnoremap <script> <C-V>' paste#paste_cmd['v']

" Use CTRL-Q to do what CTRL-V used to do
noremap <C-Q> <C-V>

" CTRL-Tab is Next window
noremap <C-Tab> <C-W>w
inoremap <C-Tab> <C-O><C-W>w
cnoremap <C-Tab> <C-C><C-W>w
onoremap <C-Tab> <C-C><C-W>w

" CTRL-F4 is Close window
noremap <C-F4> <C-W>c
inoremap <C-F4> <C-O><C-W>c
cnoremap <C-F4> <C-C><C-W>c
onoremap <C-F4> <C-C><C-W>c

" Use CTRL-S for saving, also in Insert mode
noremap <C-S>  :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

" CTRL-A is Select all
noremap <C-A> gggH<C-O>G
inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
cnoremap <C-A> <C-C>gggH<C-O>G
onoremap <C-A> <C-C>gggH<C-O>G
snoremap <C-A> <C-C>gggH<C-O>G
xnoremap <C-A> <C-C>ggVG

" Quick tab navigation
nnoremap <C-t>     :tabnew<CR>
nnoremap <C-left>  :tabp<CR>
nnoremap <C-right> :tabn<CR>

" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

" NerdTree
nnoremap <silent> <F9> :NERDTreeToggle<CR>

let NERDTreeDirArrows=1
let NERDTreeWinSize = 35
let NERDTreeAutoCenter = 1
let NERDTreeMapActivateNode='<cr>'

" Make sure that when NT root is changed, Vim's pwd is also updated
let NERDTreeChDirMode = 2

" Open NERDTree on startup, when no file has been specified
"autocmd VimEnter * if !argc() | NERDTree | endif

" Open NERDTree when Vim starts with a directory argument
function! s:FindReadme(dir) abort
    for l:ext in ['.md', '.markdown', '.rst', '.txt', '']
        for l:match in glob(a:dir . '[Rr][Ee][Aa][Dd][Mm][Ee]' . l:ext, 0, 1)
            if filereadable(l:match)
                return l:match
            endif
        endfor
    endfor
    return ''
endfunction

function! s:OpenProject(dir) abort
    let l:dir = fnamemodify(a:dir, ':p')
    execute 'NERDTree' fnameescape(l:dir)
    execute 'cd' fnameescape(l:dir)
    wincmd p
    let l:readme = s:FindReadme(l:dir)
    if empty(l:readme)
        enew
    else
        execute 'edit' fnameescape(l:readme)
    endif
endfunction

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * ++nested if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') | call s:OpenProject(argv()[0]) | endif

nnoremap <F11> :set keymap=serbian-latin<CR>
nnoremap <F10> :set keymap=<CR>

" delete trailing whitespace (spaces, tabs) from end of each line
nnoremap <silent> <F12> :%s/[ \t]*$//g<CR>

" Tab completion
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

" Force refresh completion
imap <c-space> <Plug>(asyncomplete_force_refresh)

set viminfofile=$XDG_DATA_HOME/vim/viminfo

" }}}
